In [2]:
import numpy as np
import cv2
import os

In [3]:

IMG_DIR = 'telegram_images'
FIXED_SIZE = (100, 100)  # Define a fixed size for all images

# Initialize a list to collect image arrays
all_images = []

for img in os.listdir(IMG_DIR):
    img_path = os.path.join(IMG_DIR, img)
    img_array = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    
    if img_array is None:
        print(f"Warning: Unable to read image {img_path}. Skipping.")
        continue

    # Resize the image to the fixed size
    img_array = cv2.resize(img_array, FIXED_SIZE)

    img_array = img_array.flatten()
    img_array = img_array.reshape(1, -1)
    print(img_array)

    all_images.append(img_array)

# Concatenate all image arrays vertically
if all_images:
    all_images = np.vstack(all_images)
    with open('imageoflobeli.csv', 'wb') as f:
        np.savetxt(f, all_images, delimiter=',')
else:
    print("No valid images found to write to CSV.")


[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[ 8 20  3 ...  9 25 28]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 253 253 254]]
[[254 254 254 ... 254 254 254]]
[[255 255 255 ... 255 255 255]]
[[0 0 0 ... 0 0 0]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[254 254 254 ... 254 254 254]]
[[255 255 255 ... 255 255 255]]
[[243 243 243 ... 243 243 243]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[0 0 0 ... 0 0 0]]
[[255 255 255 ... 255 255 255]]
[[254 254 254 ... 254 254 254]]
[[255 255 255 ... 255 255 255]]
[[249 249 249 ... 243 243 243]]
[[0 0 0 ... 0 0 0]]
[[ 1  1  1 ... 18 17 17]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[231 232 234 ... 235 235 234]]
[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[254 254 254 ... 254 25